<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>DATRAS Frequently Asked Questions – IMBUS</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-bba5ebae505b5c03f3f0d8040a416a6b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">IMBUS</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-background" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Background</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-background">    
        <li>
    <a class="dropdown-item" href="../IMBUS/IMBUS_proposal_summary.html">
 <span class="dropdown-text">Project Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../IMBUS/wp2_progress_review.html">
 <span class="dropdown-text">WP2 Progress Review</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-deliverables" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Deliverables</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-deliverables">    
        <li>
    <a class="dropdown-item" href="../deliverables/D2.2_data_formats_metadata.html">
 <span class="dropdown-text">D2.2 — Data Formats and Metadata</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../deliverables/D2.3_imbus_product_specification.html">
 <span class="dropdown-text">D2.3 — IMBUS Product Specification</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-datras" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">DATRAS</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-datras">    
        <li>
    <a class="dropdown-item" href="../DATRAS/reporting_format.html">
 <span class="dropdown-text">Reporting Format</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../DATRAS/DATRAS_FAQ.html">
 <span class="dropdown-text">DATRAS FAQ</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../DATRAS/DATRAS_Technical_Reference.html">
 <span class="dropdown-text">DATRAS Technical Reference</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../DATRAS/survey_indices.html">
 <span class="dropdown-text">Survey Abundance Indices</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../DATRAS/cpue_derivation.html">
 <span class="dropdown-text">CPUE derivation: CPUEL vs HL</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../DATRAS/cpuel_by_length.html">
 <span class="dropdown-text">CPUEL emulation and validation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../DATRAS/issues.html">
 <span class="dropdown-text">Data issues and QC</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../DATRAS/sampling_protocol.html">
 <span class="dropdown-text">Sampling protocols</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-meetings" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Meetings</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-meetings">    
        <li>
    <a class="dropdown-item" href="../meetings/20260601_WP2-WP5.html">
 <span class="dropdown-text">2026-06-01 WP2–WP5</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-other-projects" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Other projects</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-other-projects">    
        <li>
    <a class="dropdown-item" href="../other_projects/DATRAS_package_checks.html">
 <span class="dropdown-text">DATRAS R package — data checks</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/einarhjorleifsson/imbus"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#overview-of-datras" id="toc-overview-of-datras" class="nav-link active" data-scroll-target="#overview-of-datras">Overview of DATRAS</a>
  <ul class="collapse">
  <li><a href="#what-is-datras" id="toc-what-is-datras" class="nav-link" data-scroll-target="#what-is-datras">What is DATRAS?</a></li>
  <li><a href="#what-can-datras-data-be-used-for" id="toc-what-can-datras-data-be-used-for" class="nav-link" data-scroll-target="#what-can-datras-data-be-used-for">What can DATRAS data be used for?</a></li>
  <li><a href="#what-is-the-timespan-of-datras-data" id="toc-what-is-the-timespan-of-datras-data" class="nav-link" data-scroll-target="#what-is-the-timespan-of-datras-data">What is the timespan of DATRAS data?</a></li>
  <li><a href="#which-surveys-are-available-via-datras" id="toc-which-surveys-are-available-via-datras" class="nav-link" data-scroll-target="#which-surveys-are-available-via-datras">Which surveys are available via DATRAS?</a></li>
  <li><a href="#which-data-products-can-i-get-from-datras" id="toc-which-data-products-can-i-get-from-datras" class="nav-link" data-scroll-target="#which-data-products-can-i-get-from-datras">Which data products can I get from DATRAS?</a></li>
  <li><a href="#how-do-i-acknowledge-use-of-datras-data" id="toc-how-do-i-acknowledge-use-of-datras-data" class="nav-link" data-scroll-target="#how-do-i-acknowledge-use-of-datras-data">How do I acknowledge use of DATRAS data?</a></li>
  <li><a href="#what-are-the-data-use-restrictions" id="toc-what-are-the-data-use-restrictions" class="nav-link" data-scroll-target="#what-are-the-data-use-restrictions">What are the data use restrictions?</a></li>
  </ul></li>
  <li><a href="#for-data-users" id="toc-for-data-users" class="nav-link" data-scroll-target="#for-data-users">For Data Users</a>
  <ul class="collapse">
  <li><a href="#downloading-data" id="toc-downloading-data" class="nav-link" data-scroll-target="#downloading-data">Downloading data</a></li>
  <li><a href="#understanding-the-data-format" id="toc-understanding-the-data-format" class="nav-link" data-scroll-target="#understanding-the-data-format">Understanding the data format</a></li>
  <li><a href="#cpue-and-derived-products" id="toc-cpue-and-derived-products" class="nav-link" data-scroll-target="#cpue-and-derived-products">CPUE and derived products</a></li>
  <li><a href="#further-resources-for-data-users" id="toc-further-resources-for-data-users" class="nav-link" data-scroll-target="#further-resources-for-data-users">Further resources for data users</a></li>
  </ul></li>
  <li><a href="#for-data-submitters" id="toc-for-data-submitters" class="nav-link" data-scroll-target="#for-data-submitters">For Data Submitters</a>
  <ul class="collapse">
  <li><a href="#general" id="toc-general" class="nav-link" data-scroll-target="#general">General</a></li>
  <li><a href="#submission-process" id="toc-submission-process" class="nav-link" data-scroll-target="#submission-process">Submission process</a></li>
  <li><a href="#technical-issues-for-data-submitters" id="toc-technical-issues-for-data-submitters" class="nav-link" data-scroll-target="#technical-issues-for-data-submitters">Technical issues for data submitters</a></li>
  </ul></li>
  <li><a href="#datras-essentials" id="toc-datras-essentials" class="nav-link" data-scroll-target="#datras-essentials">DATRAS Essentials</a>
  <ul class="collapse">
  <li><a href="#contact" id="toc-contact" class="nav-link" data-scroll-target="#contact">Contact</a></li>
  <li><a href="#useful-links" id="toc-useful-links" class="nav-link" data-scroll-target="#useful-links">Useful links</a></li>
  </ul></li>
  <li><a href="#sec-annex-datatype" id="toc-sec-annex-datatype" class="nav-link" data-scroll-target="#sec-annex-datatype">Annex I: DataType examples in exchange data</a>
  <ul class="collapse">
  <li><a href="#hh-record-datatype-values" id="toc-hh-record-datatype-values" class="nav-link" data-scroll-target="#hh-record-datatype-values">HH record: DataType values</a></li>
  <li><a href="#hl-record-field-definitions" id="toc-hl-record-field-definitions" class="nav-link" data-scroll-target="#hl-record-field-definitions">HL record: field definitions</a></li>
  <li><a href="#example-1-datatype-s-1140-fish-3-species" id="toc-example-1-datatype-s-1140-fish-3-species" class="nav-link" data-scroll-target="#example-1-datatype-s-1140-fish-3-species">Example 1: DataType S — 1,140 fish, 3 species</a></li>
  <li><a href="#example-2-datatype-r-size-stratified-datatype-p-encoding" id="toc-example-2-datatype-r-size-stratified-datatype-p-encoding" class="nav-link" data-scroll-target="#example-2-datatype-r-size-stratified-datatype-p-encoding">Example 2: DataType R — size-stratified (DataType P encoding)</a></li>
  </ul></li>
  <li><a href="#sec-imbus-additions" id="toc-sec-imbus-additions" class="nav-link" data-scroll-target="#sec-imbus-additions">IMBUS Additions</a>
  <ul class="collapse">
  <li><a href="#sec-lc-na" id="toc-sec-lc-na" class="nav-link" data-scroll-target="#sec-lc-na">What do HL records with a missing <code>LengthClass</code> represent?</a></li>
  <li><a href="#sec-p-vs-r" id="toc-sec-p-vs-r" class="nav-link" data-scroll-target="#sec-p-vs-r">What is the difference between DataType “P” and “R”?</a></li>
  <li><a href="#why-do-we-have-more-than-one-value-for-speciesvalidity-within-the-same-tow-.id-for-the-same-species" id="toc-why-do-we-have-more-than-one-value-for-speciesvalidity-within-the-same-tow-.id-for-the-same-species" class="nav-link" data-scroll-target="#why-do-we-have-more-than-one-value-for-speciesvalidity-within-the-same-tow-.id-for-the-same-species">Why do we have more than one value for SpeciesValidity within the same tow (.id) for the same species?</a></li>
  </ul></li>
  <li><a href="#version-history" id="toc-version-history" class="nav-link" data-scroll-target="#version-history">Version history</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">DATRAS Frequently Asked Questions</h1>
<p class="subtitle lead">ICES Data Centre — DATRAS</p>
</div>



<div class="quarto-title-meta">

    
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">July 1, 2026</p>
    </div>
  </div>
    
  </div>
  


</header>


<blockquote class="blockquote">
<p><strong>Note on this document.</strong> This is a restructured and updated version of the ICES DATRAS FAQs (version 3.0, 2014). Field names have been updated to the current standard; legacy names are shown in parentheses. DataType <code>P</code> (size-stratified subsampling) has been added throughout. The survey list reflects the current DATRAS holdings rather than the 2014 snapshot. The source document is <code>docs_external/DATRAS_documentation/DATRAS_FAQs.pdf</code>.</p>
<p>Questions and observations marked <strong>[IMBUS]</strong> were added during the IMBUS project and are not part of the original ICES document.</p>
</blockquote>
<hr>
<section id="overview-of-datras" class="level2">
<h2 class="anchored" data-anchor-id="overview-of-datras">Overview of DATRAS</h2>
<section id="what-is-datras" class="level3">
<h3 class="anchored" data-anchor-id="what-is-datras">What is DATRAS?</h3>
<p>DATRAS is an online database of trawl surveys hosted by ICES. It stores data from internationally coordinated fish trawl surveys in ICES area 27 in a standardised format and provides a data quality check upon upload. The DATRAS portal offers online services for uploading and downloading survey data.</p>
</section>
<section id="what-can-datras-data-be-used-for" class="level3">
<h3 class="anchored" data-anchor-id="what-can-datras-data-be-used-for">What can DATRAS data be used for?</h3>
<p>DATRAS is used by ICES expert groups, national institutes, and researchers for verifying, storing, and obtaining fisheries-independent sampling data. The data can be used in stock assessments, biodiversity studies, and other fisheries-related projects. All data products are accessible under ICES Data Policy.</p>
</section>
<section id="what-is-the-timespan-of-datras-data" class="level3">
<h3 class="anchored" data-anchor-id="what-is-the-timespan-of-datras-data">What is the timespan of DATRAS data?</h3>
<p>Each survey has its own timeline. The oldest records are from 1965 (NS-IBTS). A full overview of survey coverage, including first and last year and valid haul counts, is given in the <a href="../../deliverables/D2.2_data_formats_metadata.qmd#sec-metadata">D2.2 surveys table</a>.</p>
</section>
<section id="which-surveys-are-available-via-datras" class="level3">
<h3 class="anchored" data-anchor-id="which-surveys-are-available-via-datras">Which surveys are available via DATRAS?</h3>
<p>DATRAS currently holds data from 29 surveys covering the Northeast Atlantic (as of 2026). The 2014 version of this document listed 15 surveys; the inventory has grown substantially. See the D2.2 surveys table for the full current list. Surveys include NS-IBTS, BITS, BTS, EVHOE, IE-IGFS, NIGFS, FR-CGFS, SP-NORTH, SP-PORC, SP-ARSA, PT-IBTS, and many others.</p>
</section>
<section id="which-data-products-can-i-get-from-datras" class="level3">
<h3 class="anchored" data-anchor-id="which-data-products-can-i-get-from-datras">Which data products can I get from DATRAS?</h3>
<p>All uploaded survey data can be downloaded as raw <strong>exchange data</strong> (HH, HL, CA record types). Some surveys also offer standard derived data products computed by the ICES expert groups:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Product</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>CPUEL</td>
<td>CPUE-by-length per haul</td>
</tr>
<tr class="even">
<td>CPUEA</td>
<td>CPUE-by-age per haul</td>
</tr>
<tr class="odd">
<td>IDX</td>
<td>Survey abundance indices</td>
</tr>
<tr class="even">
<td>CW</td>
<td>Catch weight by species</td>
</tr>
<tr class="odd">
<td>FL</td>
<td>Survey-specific flex file (additional fields)</td>
</tr>
<tr class="even">
<td>LT</td>
<td>Marine litter assessment</td>
</tr>
</tbody>
</table>
<p>From April 2012, all data products include a <code>DateofCalculation</code> field for tracking changes.</p>
</section>
<section id="how-do-i-acknowledge-use-of-datras-data" class="level3">
<h3 class="anchored" data-anchor-id="how-do-i-acknowledge-use-of-datras-data">How do I acknowledge use of DATRAS data?</h3>
<p>Follow the ICES Data Policy. Example citations:</p>
<blockquote class="blockquote">
<p>ICES Database of Trawl Surveys (DATRAS). ICES, Copenhagen. https://datras.ices.dk</p>
</blockquote>
<blockquote class="blockquote">
<p>ICES DATRAS, Extraction [DATE]. [Survey name] data [year range]. ICES, Copenhagen. https://datras.ices.dk</p>
</blockquote>
</section>
<section id="what-are-the-data-use-restrictions" class="level3">
<h3 class="anchored" data-anchor-id="what-are-the-data-use-restrictions">What are the data use restrictions?</h3>
<p>DATRAS data are available under the ICES open access data policy (adopted 2006, updated 2012). Aggregated data and raw data are freely available under these conditions.</p>
<hr>
</section>
</section>
<section id="for-data-users" class="level2">
<h2 class="anchored" data-anchor-id="for-data-users">For Data Users</h2>
<section id="downloading-data" class="level3">
<h3 class="anchored" data-anchor-id="downloading-data">Downloading data</h3>
<section id="how-do-i-access-trawl-survey-data" class="level4">
<h4 class="anchored" data-anchor-id="how-do-i-access-trawl-survey-data">How do I access trawl survey data?</h4>
<p>Survey data and derived products can be downloaded from the DATRAS download page. Note that the web portal limits downloads to 1 million records. For larger datasets, split the download into smaller parts (e.g.&nbsp;by year or quarter) or use the ICES web services / {obus} parquet access (<code>dr_con()</code>) for efficient bulk access without record limits.</p>
</section>
<section id="why-are-not-all-data-products-available-for-all-surveys" class="level4">
<h4 class="anchored" data-anchor-id="why-are-not-all-data-products-available-for-all-surveys">Why are not all data products available for all surveys?</h4>
<p>DATRAS data products are developed and verified in cooperation with the relevant ICES Expert Groups. This is a time-consuming process, and newer surveys may not yet have derived products. Currently CPUEL is available for 8 of the 29 surveys (BITS, EVHOE, IE-IGFS, NS-IBTS, ROCKALL, SCOROC, SCOWCGFS, SWC-IBTS).</p>
</section>
<section id="what-are-standard-species" class="level4">
<h4 class="anchored" data-anchor-id="what-are-standard-species">What are “Standard species”?</h4>
<p>Standard species are the target species of a given survey. While all surveys aim to record all species caught, each survey has one or more target species for which detailed biological data (sex, maturity, age, individual weight) are collected. Age-based data products (CPUEA, IDX) are therefore available only for standard species. Refer to the relevant survey manual for the standard species list.</p>
</section>
</section>
<section id="understanding-the-data-format" class="level3">
<h3 class="anchored" data-anchor-id="understanding-the-data-format">Understanding the data format</h3>
<section id="how-do-i-understand-the-datras-exchange-file-format" class="level4">
<h4 class="anchored" data-anchor-id="how-do-i-understand-the-datras-exchange-file-format">How do I understand the DATRAS exchange file format?</h4>
<p>Exchange data are the raw survey data as submitted by national institutes. Each file contains three record types:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 47%">
<col style="width: 52%">
</colgroup>
<thead>
<tr class="header">
<th>Record</th>
<th>Content</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>HH</strong></td>
<td>Haul Header — one row per haul; gear, position, timing, validity</td>
</tr>
<tr class="even">
<td><strong>HL</strong></td>
<td>Haul-level Length — catch by length class per species per haul</td>
</tr>
<tr class="odd">
<td><strong>CA</strong></td>
<td>Catch-at-age — individual biological measurements</td>
</tr>
</tbody>
</table>
<p>The three record types share a common set of haul identification fields and are linked by the composite haul key <code>.id</code> (constructed from <code>Survey</code>, <code>Year</code>, <code>Quarter</code>, <code>Country</code>, <code>Platform</code> (Ship), <code>Gear</code>, <code>StationName</code> (StNo), <code>HaulNumber</code> (HaulNo)). In the raw CSV submission format, these correspond to the first 11 fields common to all record types.</p>
</section>
<section id="what-does-9-stand-for" class="level4">
<h4 class="anchored" data-anchor-id="what-does-9-stand-for">What does “−9” stand for?</h4>
<p><code>−9</code> is the DATRAS sentinel value for a missing or inapplicable field. It is not a real measurement. In the IMBUS standardised product (<code>{obus}</code>, parquet files) all <code>−9</code> values are replaced with proper <code>NA</code>.</p>
</section>
<section id="what-are-haul-duration-vessel-speed-and-trawl-parameters" class="level4">
<h4 class="anchored" data-anchor-id="what-are-haul-duration-vessel-speed-and-trawl-parameters">What are haul duration, vessel speed, and trawl parameters?</h4>
<p>Standard values for <code>HaulDuration</code> (HaulDur), vessel speed, and gear parameters are defined in the survey manuals. Actual values as recorded during the haul are reported in the HH record fields <code>HaulDuration</code> (HaulDur), <code>GroundSpeed</code>, <code>Distance</code>, <code>DoorSpread</code>, <code>WingSpread</code>, and <code>WarpLength</code>.</p>
</section>
<section id="are-catch-figures-adjusted-for-hauling-time" class="level4">
<h4 class="anchored" data-anchor-id="are-catch-figures-adjusted-for-hauling-time">Are catch figures adjusted for hauling time?</h4>
<p>This depends on <code>DataType</code> in the HH record. See <a href="#sec-datatype-faq">DataType and HL field interpretation</a> for details.</p>
</section>
<section id="are-all-species-reported-in-datras" class="level4">
<h4 class="anchored" data-anchor-id="are-all-species-reported-in-datras">Are all species reported in DATRAS?</h4>
<p>Surveys intend to record all species caught, but it is the responsibility of the national data submitter whether all species are reported. The fields <code>SpeciesValidity</code> (SpecVal) in HL (field 26 in the raw HH record) and <code>SpeciesCategory</code> (CatIdentifier) (field 27) provide further context. Some surveys report a limited species list; refer to the survey manual.</p>
<p>In CA records, mainly standard survey species are reported.</p>
</section>
<section id="what-is-speciesvalidity-specval" class="level4">
<h4 class="anchored" data-anchor-id="what-is-speciesvalidity-specval">What is <code>SpeciesValidity</code> (SpecVal)?</h4>
<p><code>SpeciesValidity</code> in HL records specifies how the species was handled:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 43%">
<col style="width: 56%">
</colgroup>
<thead>
<tr class="header">
<th>Value</th>
<th>Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>1</code></td>
<td>Full record: lengths, numbers, weights — <strong>use in standard products</strong></td>
</tr>
<tr class="even">
<td><code>0</code></td>
<td>Invalid</td>
</tr>
<tr class="odd">
<td><code>4</code></td>
<td>Total number only; no lengths measured</td>
</tr>
<tr class="even">
<td><code>5</code></td>
<td>Presence/absence only</td>
</tr>
<tr class="odd">
<td><code>6</code></td>
<td>Weight only</td>
</tr>
<tr class="even">
<td><code>7</code></td>
<td>Numbers and weights; no lengths</td>
</tr>
<tr class="odd">
<td><code>10</code></td>
<td>Lengths and numbers; no weights</td>
</tr>
</tbody>
</table>
<p>Only <code>SpeciesValidity == "1"</code> records are used in DATRAS-derived data products. Records with other values may still be of value for biodiversity or non-standard analyses.</p>
<p><code>SpeciesValidity</code> is also linked to haul validity: if the haul was invalid or used for calibration, <code>SpeciesValidity</code> will reflect this.</p>
</section>
<section id="what-species-reference-system-is-used" class="level4">
<h4 class="anchored" data-anchor-id="what-species-reference-system-is-used">What species reference system is used?</h4>
<p>Species codes currently used for submissions are <strong>WoRMS AphiaIDs</strong> (<code>SpeciesCodeType</code> (SpecCodeType) = <code>"W"</code>). In historical submissions ITIS TSN (<code>"T"</code>) and NODC (<code>"N"</code>) codes were used. For cross-era analysis, all submitted codes are mapped to validated WoRMS AphiaIDs in the field <code>ValidAphiaID</code> (Valid_Aphia / Valid_WoRMS) in HL and CA records. Always use <code>ValidAphiaID</code> as the join key for species — never the raw <code>SpeciesCode</code> (SpecCode).</p>
<p>In derived data products (CPUEL, CPUEA, IDX), species are identified by valid Latin names or AphiaIDs.</p>
</section>
<section id="where-can-i-find-species-names-for-codes-in-the-file" class="level4">
<h4 class="anchored" data-anchor-id="where-can-i-find-species-names-for-codes-in-the-file">Where can I find species names for codes in the file?</h4>
<p>Species names can be matched to codes via the <a href="https://datras.ices.dk/Data_products/qryspec.aspx">DATRAS Species Query Tool</a> or directly via the <a href="https://www.marinespecies.org/">WoRMS database</a>.</p>
<p>If work in R you can also try this:</p>
<pre><code>icesVocab::findAphia(c("cod", "haddock", "saithe"))
icesVocab::findAphia("Gadus morhuha", latin = TRUE)</code></pre>
</section>
<section id="where-can-i-find-information-about-species-maximum-length" class="level4">
<h4 class="anchored" data-anchor-id="where-can-i-find-information-about-species-maximum-length">Where can I find information about species maximum length?</h4>
<p>Per-survey maximum length classes (mm) are listed on the DATRAS reporting format page (DATSU). Note that this list is static and was last updated in January 2011.</p>
</section>
<section id="what-area-codes-are-used-in-datras" class="level4">
<h4 class="anchored" data-anchor-id="what-area-codes-are-used-in-datras">What area codes are used in DATRAS?</h4>
<p>Area information appears in several places:</p>
<ul>
<li><strong>Haul positions:</strong> <code>ShootLatitude</code>/<code>ShootLongitude</code> and <code>HaulLatitude</code>/<code>HaulLongitude</code> in HH, reported as <strong>decimal degrees</strong>.</li>
<li><strong>Statistical rectangle:</strong> <code>StatisticalRectangle</code> (StatRec) in HH, based on shooting position (unless the majority of the haul was in the adjacent rectangle).</li>
<li><strong>Depth strata:</strong> <code>DepthStratum</code> (Stratum) in HH, for surveys with depth-stratified sampling.</li>
<li><strong>Age-sampling areas:</strong> <code>AreaCode</code> and <code>AreaType</code> in CA, indicating whether the age sample is haul-level (<code>AreaType == "H"</code>) or area-pooled. Always check <code>AreaType</code> before joining CA records to HH.</li>
</ul>
<p>ICES statistical rectangles are described at the <a href="https://www.ices.dk/marine-data/maps/Pages/ICES-statistical-rectangles.aspx">ICES maps page</a>.</p>
</section>
<section id="do-datras-data-pass-any-quality-validation" class="level4">
<h4 class="anchored" data-anchor-id="do-datras-data-pass-any-quality-validation">Do DATRAS data pass any quality validation?</h4>
<p>Yes. Before upload, all files pass the <strong>DATSU</strong> screening utility, which applies logical, value, and vocabulary checks. Critical errors must be corrected before the file can be uploaded; warnings are non-critical. Weight-length outlier graphs are also provided as an additional screening tool.</p>
<p>Every year, responsible expert groups review their data and report irrelevancies to the DATRAS team. If you find erroneous data, contact DATRAS administration (DATRASAdministration@ices.dk).</p>
</section>
</section>
<section id="cpue-and-derived-products" class="level3">
<h3 class="anchored" data-anchor-id="cpue-and-derived-products">CPUE and derived products</h3>
<section id="what-is-cpue-in-datras" class="level4">
<h4 class="anchored" data-anchor-id="what-is-cpue-in-datras">What is CPUE in DATRAS?</h4>
<p>CPUE (catch per unit effort) in DATRAS is the catch in numbers of individuals of the same species, adjusted to <strong>one hour of hauling</strong>.</p>
</section>
<section id="if-i-compare-cpue-per-length-values-to-the-exchange-file-they-dont-match.-why" class="level4">
<h4 class="anchored" data-anchor-id="if-i-compare-cpue-per-length-values-to-the-exchange-file-they-dont-match.-why">If I compare CPUE per length values to the exchange file, they don’t match. Why?</h4>
<p>Exchange files contain data as submitted, potentially in DataType R (raw), S (sub-sampled), or C (catch per unit effort). CPUE data products display numbers raised to one hour of hauling. To compare, you must apply the appropriate raising formula to the exchange data. See <a href="#sec-datatype-faq">DataType and HL field interpretation</a> for the correct formula per DataType.</p>
</section>
<section id="what-do-zeroes-mean-in-a-cpue-product" class="level4">
<h4 class="anchored" data-anchor-id="what-do-zeroes-mean-in-a-cpue-product">What do zeroes mean in a CPUE product?</h4>
<p>A CPUE value of zero means the species was <strong>absent</strong> from that haul but was caught by at least one vessel in the same survey/year/quarter. Zero records are automatically added to all hauls where the species was absent. Explicit zero rows are required for unbiased abundance indices.</p>
<p>A species may also have a zero if the data submitter observed but did not record biological data. Refer to the exchange file for details.</p>
</section>
<section id="a-species-is-missing-from-cpue-for-some-yearsquarters.-why" class="level4">
<h4 class="anchored" data-anchor-id="a-species-is-missing-from-cpue-for-some-yearsquarters.-why">A species is missing from CPUE for some years/quarters. Why?</h4>
<p>Records for a species in a CPUE product appear only if at least one submitter observed and reported it in that year/quarter. If no submitter reported the species in a given year/quarter, no records (including zeroes) will be present in the product.</p>
</section>
<section id="why-are-age-records-limited-to-age_6-or-age_10-in-age-based-products" class="level4">
<h4 class="anchored" data-anchor-id="why-are-age-records-limited-to-age_6-or-age_10-in-age-based-products">Why are age records limited to age_6 or age_10 in age-based products?</h4>
<p>Age-based products are designed according to requirements from the responsible ICES Expert Group. Groups specify a <strong>plus group</strong> age, above which all fish are aggregated (e.g.&nbsp;NS-IBTS uses plus group age 6: all fish aged 6+ are recorded as age 6).</p>
</section>
<section id="what-is-country-code-dum-dummy" class="level4">
<h4 class="anchored" data-anchor-id="what-is-country-code-dum-dummy">What is country code DUM (DUMMY)?</h4>
<p>Country code <code>DUM</code> was used for reporting historical age data from Danish commercial vessels with platform codes <code>DCA</code> and <code>HOL</code> in 1983–1995.</p>
</section>
<section id="where-are-bits-data-before-1991" class="level4">
<h4 class="anchored" data-anchor-id="where-are-bits-data-before-1991">Where are BITS data before 1991?</h4>
<p>BITS started in the early 1980s but was not standardised until 1991. The responsible expert group (WGBIFS) decided that only data from 1991 onward should be available via DATRAS. Contact WGBIFS for access to earlier data.</p>
</section>
<section id="where-do-i-find-survey-abundance-indices" class="level4">
<h4 class="anchored" data-anchor-id="where-do-i-find-survey-abundance-indices">Where do I find survey abundance indices?</h4>
<p>DATRAS provides CPUE-by-length and CPUE-by-age products for standard species. These are accessible via <code>dr_get("IDX", ...)</code> in {obus}. Note that no weight-based products are currently available from DATRAS.</p>
</section>
<section id="is-there-a-tool-to-convert-age-to-weight" class="level4">
<h4 class="anchored" data-anchor-id="is-there-a-tool-to-convert-age-to-weight">Is there a tool to convert age to weight?</h4>
<p>Not directly. You can use the CA records (including individual weight measurements where available) to construct your own age–weight relationship.</p>
</section>
<section id="can-i-see-when-data-were-last-corrected" class="level4">
<h4 class="anchored" data-anchor-id="can-i-see-when-data-were-last-corrected">Can I see when data were last corrected?</h4>
<p>The DATRAS Submission Status page shows when the last cruise submission was made. The current DATRAS version does not show what was changed in a re-submission.</p>
</section>
</section>
<section id="further-resources-for-data-users" class="level3">
<h3 class="anchored" data-anchor-id="further-resources-for-data-users">Further resources for data users</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Topic</th>
<th>Resource</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Survey manuals</td>
<td>DATRAS Documents section</td>
</tr>
<tr class="even">
<td>ICES Expert Groups</td>
<td><a href="https://ices.dk/community/groups">ices.dk/community/groups</a></td>
</tr>
<tr class="odd">
<td>ICES stock advice</td>
<td><a href="https://www.ices.dk/advice">ices.dk/advice</a></td>
</tr>
<tr class="even">
<td>TACs, stocks, quotas</td>
<td>EU Fisheries; NEAFC</td>
</tr>
<tr class="odd">
<td>Commercial catches</td>
<td><a href="https://www.ices.dk/marine-data/dataset-collections/Pages/Fish-catch-and-stock-assessment.aspx">ICES catch statistics</a></td>
</tr>
<tr class="even">
<td>Marine environmental data</td>
<td><a href="https://ecosystemdata.ices.dk/">ICES Data Portal</a></td>
</tr>
</tbody>
</table>
<hr>
</section>
</section>
<section id="for-data-submitters" class="level2">
<h2 class="anchored" data-anchor-id="for-data-submitters">For Data Submitters</h2>
<section id="general" class="level3">
<h3 class="anchored" data-anchor-id="general">General</h3>
<section id="what-is-the-deadline-for-my-submission" class="level4">
<h4 class="anchored" data-anchor-id="what-is-the-deadline-for-my-submission">What is the deadline for my submission?</h4>
<p>Submission deadlines are listed on the DATRAS home page. Contact DATRAS administration if you are unsure.</p>
</section>
<section id="how-should-my-data-file-be-formatted" class="level4">
<h4 class="anchored" data-anchor-id="how-should-my-data-file-be-formatted">How should my data file be formatted?</h4>
<p>DATRAS accepts <strong>CSV</strong> files (comma-separated, decimal point <code>.</code>, no blank fields — use <code>−9</code> for missing values, no headers). One file should contain all record types (HH, HL, CA) for the same year, quarter, country, vessel, and gear. All fields from the reporting format must be present.</p>
</section>
<section id="which-units-and-codes-should-be-used" class="level4">
<h4 class="anchored" data-anchor-id="which-units-and-codes-should-be-used">Which units and codes should be used?</h4>
<p>Field descriptions, units, and valid codes are in the DATRAS Reporting Format documentation and in the ICES Vocabulary Server (https://vocab.ices.dk/). Within {obus}, valid codes are also available via <code>dr_lookup_vocabulary</code>.</p>
</section>
<section id="how-do-i-get-access-to-the-datras-upload-page" class="level4">
<h4 class="anchored" data-anchor-id="how-do-i-get-access-to-the-datras-upload-page">How do I get access to the DATRAS upload page?</h4>
<p>Write to DATRAS administration and the Chair of the associated ICES Expert Group with your submitter details and access request.</p>
</section>
</section>
<section id="submission-process" class="level3">
<h3 class="anchored" data-anchor-id="submission-process">Submission process</h3>
<section id="how-do-i-submit-my-file" class="level4">
<h4 class="anchored" data-anchor-id="how-do-i-submit-my-file">How do I submit my file?</h4>
<p>Direct upload is available for most surveys from the DATRAS uploading page. Follow the instructions in “How to upload data into DATRAS” (available in the Documents section).</p>
</section>
<section id="what-quality-control-does-my-file-pass" class="level4">
<h4 class="anchored" data-anchor-id="what-quality-control-does-my-file-pass">What quality control does my file pass?</h4>
<p>Files pass the <strong>DATSU</strong> screening utility before upload:</p>
<ul>
<li><strong>Critical errors</strong> must be corrected; the file cannot be uploaded until they are resolved.</li>
<li><strong>Warnings</strong> are non-critical; the submitter decides whether to correct them.</li>
<li><strong>Information messages</strong> do not affect uploading.</li>
</ul>
<p>Screening results are displayed on the DATRAS page and sent to the submitter’s email. If a screening message is unclear, click the question mark in the screening results table for more detail. If still unclear, contact DATRAS administration with your file and a screenshot.</p>
</section>
<section id="what-is-error-grouping-in-datsu" class="level4">
<h4 class="anchored" data-anchor-id="what-is-error-grouping-in-datsu">What is error grouping in DATSU?</h4>
<p>When the same error occurs many times, DATSU groups them into a single entry with a count. The submitter can expand the group to see individual occurrences. This avoids scrolling through thousands of identical messages.</p>
</section>
<section id="i-get-the-survey-selected-does-not-include-the-country-present-in-the-file.-what-is-wrong" class="level4">
<h4 class="anchored" data-anchor-id="i-get-the-survey-selected-does-not-include-the-country-present-in-the-file.-what-is-wrong">I get “the survey selected does not include the country present in the file”. What is wrong?</h4>
<p>Check:</p>
<ol type="1">
<li>The country code matches the vocabulary at https://vocab.ices.dk/?ref=4.</li>
<li>Numbers use a decimal <strong>point</strong> (<code>.</code>), not a decimal comma.</li>
<li>Your account has upload rights for this survey. Contact DATRAS administration if not.</li>
</ol>
</section>
<section id="i-cannot-find-my-uploaded-data-on-the-download-page." class="level4">
<h4 class="anchored" data-anchor-id="i-cannot-find-my-uploaded-data-on-the-download-page.">I cannot find my uploaded data on the download page.</h4>
<p>Check the DATRAS Submission Status page. If your submission is listed there with the correct upload time, the upload was successful. Updates to the download page may take a few days due to manual quality-control processing. If the data are needed urgently, contact DATRAS administration.</p>
</section>
<section id="can-i-make-a-partial-re-submission-by-haul-or-record-type" class="level4">
<h4 class="anchored" data-anchor-id="can-i-make-a-partial-re-submission-by-haul-or-record-type">Can I make a partial re-submission by haul or record type?</h4>
<p>No.&nbsp;DATRAS requires a complete re-submission per year, quarter, country, vessel, and gear.</p>
</section>
<section id="what-happens-to-existing-data-when-i-re-submit" class="level4">
<h4 class="anchored" data-anchor-id="what-happens-to-existing-data-when-i-re-submit">What happens to existing data when I re-submit?</h4>
<p>Existing data are overwritten when the data warehouse is updated. Always keep a copy of previous submissions. Note: if you re-submit with different key values (year, quarter, country, vessel, gear), the old data will <strong>not</strong> be overwritten — contact DATRAS administration to remove duplicates.</p>
</section>
<section id="can-i-document-what-was-changed-in-a-re-submission" class="level4">
<h4 class="anchored" data-anchor-id="can-i-document-what-was-changed-in-a-re-submission">Can I document what was changed in a re-submission?</h4>
<p>Yes — use the remarks box at the final upload step. You are also welcome to email DATRAS administration describing the corrections made.</p>
</section>
</section>
<section id="technical-issues-for-data-submitters" class="level3">
<h3 class="anchored" data-anchor-id="technical-issues-for-data-submitters">Technical issues for data submitters</h3>
<section id="sec-datatype-faq" class="level4">
<h4 class="anchored" data-anchor-id="sec-datatype-faq">DataType and HL field interpretation</h4>
<p><code>DataType</code> is set at the haul level (HH record) and governs how HL fields must be interpreted. It is the most common source of silent errors when working with exchange data.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 27%">
<col style="width: 35%">
<col style="width: 37%">
</colgroup>
<thead>
<tr class="header">
<th>DataType</th>
<th>Description</th>
<th>CPUE formula</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>R</code></td>
<td>Raw; catch sorted, some species may be sub-sampled. <code>SubsamplingFactor</code> ≥ 1</td>
<td><code>n_haul = Σ(NumberAtLength × SubsamplingFactor)</code></td>
</tr>
<tr class="even">
<td><code>S</code></td>
<td>Bulk unsorted catch sub-sampled before sorting. <code>SubsamplingFactor</code> &gt; 1</td>
<td>Same as R</td>
</tr>
<tr class="odd">
<td><code>P</code></td>
<td>Size-stratified subsampling — different <code>SubsamplingFactor</code> per size grade. <strong>Do not sum <code>TotalNumber</code> across strata.</strong></td>
<td>Same row-level formula as R, applied per stratum</td>
</tr>
<tr class="even">
<td><code>C</code></td>
<td>Catch pre-raised to 1 hour of hauling. <code>SubsamplingFactor</code> = 1</td>
<td><code>n_hour = NumberAtLength</code>; <code>n_haul = NumberAtLength × HaulDuration / 60</code></td>
</tr>
</tbody>
</table>
<p>The <code>{obus}</code> function <code>dr_HL_standardised()</code> applies the correct formula for all DataTypes automatically. For full field-by-field specifications and empirical notes on DataType misuse in submissions, see <a href="../DATRAS/DATRAS_Technical_Reference.html#sec-datatype">DATRAS Technical Reference §DataType</a>.</p>
</section>
<section id="what-is-speciescategory-catidentifier-and-how-do-i-use-it" class="level4">
<h4 class="anchored" data-anchor-id="what-is-speciescategory-catidentifier-and-how-do-i-use-it">What is <code>SpeciesCategory</code> (CatIdentifier), and how do I use it?</h4>
<p><code>SpeciesCategory</code> (CatIdentifier) is the ID assigned to a size- or weight-based subsampling stratum for a given species and sex within a haul. It is used when a truly representative sub-sample cannot be selected from the whole catch — for example, when larger fish are sorted away and measured separately with a different sub-sampling factor.</p>
<ul>
<li>Assign <code>SpeciesCategory = 1</code> to the first stratum and <code>SpeciesCategory = 2</code>, <code>3</code>, … to additional strata (up to 5 per species per haul).</li>
<li>If no size categorisation was applied, use <code>SpeciesCategory = 1</code> throughout.</li>
<li>Reporting different <strong>sex</strong> categories for the same species does not require different <code>SpeciesCategory</code> values — keep <code>SpeciesCategory = 1</code> and vary <code>SpeciesSex</code> (Sex) instead.</li>
</ul>
<p>See the NS-IBTS survey manual (section “Length composition”) for worked examples.</p>
</section>
<section id="how-is-daynight-defined" class="level4">
<h4 class="anchored" data-anchor-id="how-is-daynight-defined">How is Day/Night defined?</h4>
<p>Daytime is defined as the period from 15 minutes before sunrise to 15 minutes after sunset, following NOAA’s solar calculations. The derived field <code>DayNight</code> in HH is populated by the ICES datacenter from the shooting position and time.</p>
</section>
<section id="which-areaposition-should-i-report" class="level4">
<h4 class="anchored" data-anchor-id="which-areaposition-should-i-report">Which area/position should I report?</h4>
<ul>
<li><strong>Coordinates:</strong> <code>ShootLatitude</code>/<code>ShootLongitude</code> and <code>HaulLatitude</code>/<code>HaulLongitude</code> in HH, as <strong>decimal degrees</strong>.</li>
<li><strong>Statistical rectangle:</strong> <code>StatisticalRectangle</code> (StatRec) in HH, based on shooting position.</li>
<li><strong>Depth strata:</strong> <code>DepthStratum</code> (Stratum) in HH, if sampling is depth-stratified.</li>
<li><strong>CA area codes:</strong> <code>AreaCode</code> and <code>AreaType</code> in CA, specifying haul-level vs.&nbsp;area-pooled age sampling.</li>
</ul>
</section>
<section id="how-do-i-submit-area-based-ca-data-without-corresponding-hl-data" class="level4">
<h4 class="anchored" data-anchor-id="how-do-i-submit-area-based-ca-data-without-corresponding-hl-data">How do I submit area-based CA data without corresponding HL data?</h4>
<p>CA records must always be related to a parent HL record. If age sampling was area-based, create a <strong>dummy HL record</strong> by duplicating fields 2–12 from the CA record and setting all other HL fields to <code>−9</code>.</p>
<p>Example CA record:</p>
<pre><code>CA,1,SCO,SCO3,GOV,60,-9,P,S01,1,2010,W,126417,2,3,0,140,U,-9,-9,3,1,-9</code></pre>
<p>Corresponding dummy HL record:</p>
<pre><code>HL,1,SCO,SCO3,GOV,60,-9,P,S01,1,2010,W,126417,0,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9</code></pre>
</section>
<section id="species-codes-and-speciescodetype-speccodetype" class="level4">
<h4 class="anchored" data-anchor-id="species-codes-and-speciescodetype-speccodetype">Species codes and <code>SpeciesCodeType</code> (SpecCodeType)</h4>
<p>Current submissions use WoRMS AphiaIDs (<code>SpeciesCodeType = "W"</code>). Historical data used ITIS TSN (<code>"T"</code>) and NODC (<code>"N"</code>) codes. All codes are mapped to current WoRMS AphiaIDs in the field <code>ValidAphiaID</code> (Valid_Aphia / Valid_WoRMS). For all analysis, use <code>ValidAphiaID</code> as the species join key.</p>
<hr>
</section>
</section>
</section>
<section id="datras-essentials" class="level2">
<h2 class="anchored" data-anchor-id="datras-essentials">DATRAS Essentials</h2>
<section id="contact" class="level3">
<h3 class="anchored" data-anchor-id="contact">Contact</h3>
<p>DATRAS helpdesk: <a href="mailto:DATRASAdministration@ices.dk" class="email">DATRASAdministration@ices.dk</a><br>
Phone: +45 3338 6700</p>
</section>
<section id="useful-links" class="level3">
<h3 class="anchored" data-anchor-id="useful-links">Useful links</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 66%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Resource</th>
<th>URL</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>DATRAS home</td>
<td>https://www.ices.dk/data/data-portals/Pages/DATRAS.aspx</td>
</tr>
<tr class="even">
<td>DATRAS download</td>
<td>https://datras.ices.dk/Data_products/Download/Download_Data_public.aspx</td>
</tr>
<tr class="odd">
<td>DATRAS reporting formats</td>
<td>https://datras.ices.dk/Data_products/ReportingFormat.aspx</td>
</tr>
<tr class="even">
<td>DATRAS submission status</td>
<td>https://datras.ices.dk/Data_products/Submission_Status.aspx</td>
</tr>
<tr class="odd">
<td>DATRAS web services</td>
<td>https://datras.ices.dk/WebServices/Webservices.aspx</td>
</tr>
<tr class="even">
<td>DATRAS documents</td>
<td>https://www.ices.dk/data/data-portals/Pages/DATRAS-docs.aspx</td>
</tr>
<tr class="odd">
<td>DATRAS species query</td>
<td>https://datras.ices.dk/Data_products/qryspec.aspx</td>
</tr>
<tr class="even">
<td>ICES Vocabulary Server</td>
<td>https://vocab.ices.dk/</td>
</tr>
<tr class="odd">
<td>ICES Data Policy</td>
<td>https://www.ices.dk/data/guidelines-and-policy/pages/ices-data-policy.aspx</td>
</tr>
<tr class="even">
<td>ICES Data Portal</td>
<td>https://www.ices.dk/data/data-portals/Pages/default.aspx</td>
</tr>
<tr class="odd">
<td>ICES Geonetwork</td>
<td><del>https://geo.ices.dk/geonetwork</del></td>
</tr>
<tr class="even">
<td>WoRMS database</td>
<td>https://www.marinespecies.org/</td>
</tr>
<tr class="odd">
<td>NOAA Solar Calculator</td>
<td>https://www.esrl.noaa.gov/gmd/grad/solcalc/</td>
</tr>
<tr class="even">
<td>NEAFC</td>
<td>https://www.neafc.org/</td>
</tr>
<tr class="odd">
<td>ICES catch statistics</td>
<td><del>https://www.ices.dk/marine-data/dataset-collections/Pages/Fish-catch-and-stock-assessment.aspx</del></td>
</tr>
</tbody>
</table>
<hr>
</section>
</section>
<section id="sec-annex-datatype" class="level2">
<h2 class="anchored" data-anchor-id="sec-annex-datatype">Annex I: DataType examples in exchange data</h2>
<section id="hh-record-datatype-values" class="level3">
<h3 class="anchored" data-anchor-id="hh-record-datatype-values">HH record: DataType values</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 43%">
<col style="width: 56%">
</colgroup>
<thead>
<tr class="header">
<th>DataType</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>S</code></td>
<td>Sub-sampled: catch sub-sampled before sorting; all <code>SubsamplingFactor</code> (SubFactor) values &gt; 1</td>
</tr>
<tr class="even">
<td><code>R</code></td>
<td>Recorded by haul: catch sorted; some species may be sub-sampled; <code>SubsamplingFactor</code> ≥ 1</td>
</tr>
<tr class="odd">
<td><code>P</code></td>
<td>Size-stratified (pseudocategory): different <code>SubsamplingFactor</code> per size stratum within a species; uses <code>SpeciesCategory</code> (CatIdentifier) to label strata</td>
</tr>
<tr class="even">
<td><code>C</code></td>
<td>CPUE: data pre-raised to one hour of hauling; all <code>SubsamplingFactor</code> = 1</td>
</tr>
</tbody>
</table>
</section>
<section id="hl-record-field-definitions" class="level3">
<h3 class="anchored" data-anchor-id="hl-record-field-definitions">HL record: field definitions</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 42%">
<col style="width: 25%">
<col style="width: 32%">
</colgroup>
<thead>
<tr class="header">
<th>Field (new name)</th>
<th>Old name</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>SubsamplingFactor</code></td>
<td>SubFactor</td>
<td>Sub-sampling factor by haul, species, sex, and <code>SpeciesCategory</code></td>
</tr>
<tr class="even">
<td><code>NumberAtLength</code></td>
<td>HLNoAtLngt</td>
<td>Number of fish measured in the (sub-)sample at this length class</td>
</tr>
<tr class="odd">
<td><code>SubsampledNumber</code></td>
<td>NoMeas</td>
<td>Sum of <code>NumberAtLength</code> across length classes, by haul × species × sex × <code>SpeciesCategory</code></td>
</tr>
<tr class="even">
<td><code>TotalNumber</code></td>
<td>TotalNo</td>
<td><code>SubsamplingFactor</code> × <code>SubsampledNumber</code> (DataType R/S/P); raised count per hour (DataType C)</td>
</tr>
</tbody>
</table>
</section>
<section id="example-1-datatype-s-1140-fish-3-species" class="level3">
<h3 class="anchored" data-anchor-id="example-1-datatype-s-1140-fish-3-species">Example 1: DataType S — 1,140 fish, 3 species</h3>
<pre><code>Catch: 1,140 fish   SubsamplingFactor = 2
→ Measure 570 fish (sub-sample)

  400 Plaice          150 Whiting         20 Cod
  SubFactor = 2       SubFactor = 8       SubFactor = 1
  NoMeas = 200        NoMeas = 75/2 = ...  NoMeas = 20
  Measure 200         Measure sub-sample   Measure all 20</code></pre>
<p>For Plaice:<br>
<code>TotalNumber</code> = 400, <code>SubsamplingFactor</code> = 2, <code>SubsampledNumber</code> = 200<br>
Verify: 400 = 200 × 2 ✓<br>
<code>NumberAtLength</code> values sum to 200 (= <code>SubsampledNumber</code>) ✓</p>
</section>
<section id="example-2-datatype-r-size-stratified-datatype-p-encoding" class="level3">
<h3 class="anchored" data-anchor-id="example-2-datatype-r-size-stratified-datatype-p-encoding">Example 2: DataType R — size-stratified (DataType P encoding)</h3>
<p>Species with two size grades in one haul:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th><code>SpeciesCategory</code> (CatIdentifier)</th>
<th>Size range</th>
<th><code>SubsamplingFactor</code> (SubFactor)</th>
<th>Fish measured</th>
<th><code>TotalNumber</code> (TotalNo)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Small (100–160 mm)</td>
<td>5.9</td>
<td>61</td>
<td>≈ 360</td>
</tr>
<tr class="even">
<td>2</td>
<td>Large (210–420 mm)</td>
<td>1.0</td>
<td>168</td>
<td>168</td>
</tr>
</tbody>
</table>
<p>Correct haul total: <strong>360 + 168 = 528 fish</strong><br>
Formula: <code>n_haul = Σ(NumberAtLength × SubsamplingFactor)</code> applied row by row — correct for all DataTypes including size-stratified R and P hauls.<br>
<strong>Do not sum <code>TotalNumber</code> across <code>SpeciesCategory</code> strata</strong> — it is the stratum total.</p>
<hr>
</section>
</section>
<section id="sec-imbus-additions" class="level2">
<h2 class="anchored" data-anchor-id="sec-imbus-additions">IMBUS Additions</h2>
<p>The questions below were not in the original ICES FAQ. They arose from exploratory analysis of the DATRAS exchange tables conducted as part of IMBUS WP2.</p>
<section id="sec-lc-na" class="level3">
<h3 class="anchored" data-anchor-id="sec-lc-na">What do HL records with a missing <code>LengthClass</code> represent?</h3>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>[IMBUS]</strong> This question was not in the original ICES FAQ. It arose from IMBUS WP2 exploratory analysis of the DATRAS HL table.</p>
</div>
</div>
<p>In the HL exchange table, records where <code>LengthClass</code> is <code>NA</code> (encoded as <code>−9</code> in raw CSV files) are <strong>catch-totals rows</strong>. They record aggregate catch information for a species within a haul but carry no individual length measurement. Every such row also has <code>NumberAtLength = NA</code>. They are distinct from length-frequency rows in both purpose and content.</p>
<p>Catch-totals rows typically carry one or more of:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 43%">
<col style="width: 56%">
</colgroup>
<thead>
<tr class="header">
<th>Field</th>
<th>Content</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>TotalNumber</code></td>
<td>Total count of fish in the haul (raised; or per hour for DataType C)</td>
</tr>
<tr class="even">
<td><code>SubsampledNumber</code></td>
<td>Number of fish actually handled or weighed</td>
</tr>
<tr class="odd">
<td><code>SpeciesCategoryWeight</code></td>
<td>Catch weight for the species/category</td>
</tr>
<tr class="even">
<td><code>SubsamplingFactor</code></td>
<td>Raising factor (may be 1 if all fish were counted)</td>
</tr>
</tbody>
</table>
<p>These rows arise in two situations:</p>
<ol type="1">
<li><strong>Species measured by count or weight only</strong> — where <code>SpeciesValidity</code> ≠ 1 (e.g.&nbsp;<code>4</code> = total number only, <code>6</code> = weight only, <code>7</code> = numbers and weights but no lengths). In this case the catch-totals row <em>is</em> the only HL record for that species.</li>
<li><strong>Companion summary rows</strong> — present alongside a full length-frequency series for the same species/haul (typically <code>SpeciesValidity = 1</code>). The catch-totals row then summarises what the length rows describe individually.</li>
</ol>
<p><strong>Key implication for analysis:</strong> always filter <code>!is.na(LengthClass)</code> (and <code>!is.na(NumberAtLength)</code>) before computing CPUE or length distributions. Catch-totals rows cannot be raised via <code>sum(NumberAtLength × SubsamplingFactor)</code> — they carry no <code>NumberAtLength</code>. The <code>{obus}</code> function <code>dr_add_n_and_cpue()</code> handles this automatically.</p>
<p><code>TotalNumber</code> in catch-totals rows is useful as a cross-check against the raised sum from the length-frequency rows, but note that its scope (all-sex total vs.&nbsp;sex-specific) is not consistent across surveys; see the <a href="../DATRAS/issues.html#sec-totalnumber-reconciliation">DATRAS data issues</a> for a survey-by-survey reconciliation.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 5
  n_records n_NA_NumberAtLength n_has_TotalNumber n_has_SubsampledNumber
      &lt;dbl&gt;               &lt;dbl&gt;             &lt;dbl&gt;                  &lt;dbl&gt;
1    377693              377693            278306                 124877
# ℹ 1 more variable: n_has_SpeciesCatWeight &lt;dbl&gt;</code></pre>
</div>
</div>
</section>
<section id="sec-p-vs-r" class="level3">
<h3 class="anchored" data-anchor-id="sec-p-vs-r">What is the difference between DataType “P” and “R”?</h3>
<p><strong>Short answer:</strong> DataType <strong>R</strong> (raw catch) is for hauls where the entire catch is sorted and some species are sub-sampled at a <strong>single</strong> rate. DataType <strong>P</strong> (pseudocategory) is for hauls where the catch is sorted into <strong>multiple size grades</strong>, each with its own sub-sampling rate.</p>
<p><strong>When you would encounter each:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>DataType</th>
<th>Scenario</th>
<th>Sub-sampling approach</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>R</strong></td>
<td>Regular haul</td>
<td>One species, one sub-sample rate per species</td>
</tr>
<tr class="even">
<td><strong>P</strong></td>
<td>Size-stratified</td>
<td>One species, <strong>multiple size grades</strong>, each grade sub-sampled separately</td>
</tr>
<tr class="odd">
<td><strong>S</strong></td>
<td>Bulk sub-sample</td>
<td>Entire catch sub-sampled before sorting</td>
</tr>
<tr class="even">
<td><strong>C</strong></td>
<td>Pre-raised</td>
<td>Lab already converted to CPUE (per hour)</td>
</tr>
</tbody>
</table>
<p><strong>Example: same species, two size grades in one haul</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>DataType</th>
<th><code>SpeciesCategory</code></th>
<th>Size range</th>
<th><code>SubsamplingFactor</code></th>
<th>Measured</th>
<th><code>TotalNumber</code></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>P</strong></td>
<td>1</td>
<td>Small (100–160 mm)</td>
<td>5.9</td>
<td>61</td>
<td>≈ 360</td>
</tr>
<tr class="even">
<td></td>
<td>2</td>
<td>Large (210–420 mm)</td>
<td>1.0</td>
<td>168</td>
<td>168</td>
</tr>
</tbody>
</table>
<p>For both P and R, calculate haul total identically: <code>n_haul = Σ(NumberAtLength × SubsamplingFactor)</code> per row = (61 × 5.9) + (168 × 1.0) = 528 fish.</p>
<p><strong>Why the distinction exists:</strong></p>
<ul>
<li><strong>DataType P explicitly signals</strong> that size-stratification is present, so downstream users understand that multiple <code>SpeciesCategory</code> rows per species per haul are expected, and each <code>TotalNumber</code> corresponds to a size stratum.</li>
<li><strong>DataType R</strong> signals that there is one sub-sampling rate per species; users can be confident that summing by species will yield the haul total.</li>
</ul>
<p><strong>Recommended practice for users:</strong> - Always use the row-level formula: <code>n_haul = Σ(NumberAtLength × SubsamplingFactor)</code> per haul and species - The <code>{obus}</code> function <code>dr_add_n_and_cpue()</code> handles all DataTypes correctly</p>
</section>
<section id="why-do-we-have-more-than-one-value-for-speciesvalidity-within-the-same-tow-.id-for-the-same-species" class="level3">
<h3 class="anchored" data-anchor-id="why-do-we-have-more-than-one-value-for-speciesvalidity-within-the-same-tow-.id-for-the-same-species">Why do we have more than one value for SpeciesValidity within the same tow (.id) for the same species?</h3>
<p><code>SpeciesValidity</code> is a <strong>record type</strong> field — it describes <em>what kind of data</em> is present for a species within a haul, not whether the haul is valid. The HL exchange format allows more than one record type for the same species and haul, and some surveys use this deliberately.</p>
<p>A typical scenario: a species was fully length-measured (<code>"1"</code>, full record), but the crew also recorded a total count for a size group that was not individually measured (<code>"4"</code>, total number only), or noted a presence/absence for bycatch (<code>"5"</code>). Both rows share the same <code>.id × aphia</code> group, so <code>SpeciesValidity</code> is not constant within that group.</p>
<p>This is <strong>intentional, not an error</strong>. BTS and Can-Mar are the main surveys that submit multiple record types for the same species and haul. Across all surveys, ~2,786 of ~2.6 million HL groups (0.1%) show this pattern. The most common co-occurrences are <code>{1, 5}</code> and <code>{4, 7}</code>.</p>
<p><strong>Worked example.</strong> The following rows are taken directly from haul <code>BTS:2024:3:BE:1186:BT4S:40:1</code> for <em>Sepia officinalis</em> (aphia 141444, common cuttlefish). Only the <code>DevelopmentStage = NA</code> rows are shown (the egg rows, <code>DevelopmentStage = "E"</code>, follow the same pattern):</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;"><code>LengthClass</code></th>
<th style="text-align: center;"><code>NumberAtLength</code></th>
<th style="text-align: center;"><code>TotalNumber</code></th>
<th style="text-align: center;"><code>SpeciesValidity</code></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">10</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">18</td>
<td style="text-align: center;"><strong>1</strong></td>
</tr>
<tr class="even">
<td style="text-align: center;">15</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">18</td>
<td style="text-align: center;"><strong>1</strong></td>
</tr>
<tr class="odd">
<td style="text-align: center;">20</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">18</td>
<td style="text-align: center;"><strong>1</strong></td>
</tr>
<tr class="even">
<td style="text-align: center;">25</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">18</td>
<td style="text-align: center;"><strong>1</strong></td>
</tr>
<tr class="odd">
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">18</td>
<td style="text-align: center;"><strong>1</strong></td>
</tr>
<tr class="even">
<td style="text-align: center;">110</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">18</td>
<td style="text-align: center;"><strong>1</strong></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><code>NA</code></td>
<td style="text-align: center;"><code>NA</code></td>
<td style="text-align: center;">18</td>
<td style="text-align: center;"><strong>5</strong></td>
</tr>
</tbody>
</table>
<p>The ten <code>SpeciesValidity = "1"</code> rows carry the full length-frequency distribution (<code>LengthClass</code> 10–110 mm, <code>NumberAtLength</code> filled). The final row, <code>SpeciesValidity = "5"</code>, is a supplementary presence/absence marker: it carries no length or count data of its own (<code>LengthClass = NA</code>, <code>NumberAtLength = NA</code>) but coexists in the same <code>.id × aphia</code> group. This is the <strong>intended semantics</strong> of <code>SpeciesValidity = "5"</code> as defined in the DATRAS format.</p>
<p><strong>Can-Mar exception.</strong> Can-Mar uses <code>SpeciesValidity = "5"</code> differently — on rows that carry actual <code>LengthClass</code> and <code>NumberAtLength</code> values. Across 535 Can-Mar groups with both <code>"1"</code> and <code>"5"</code> rows containing length data, 42% have entirely distinct length classes between the two record types (the <code>"5"</code> rows add lengths not in the <code>"1"</code> rows), 20% are full duplicates, and 38% partially overlap. The reason for this split is not documented in the DATRAS submission format. Filtering to <code>SpeciesValidity == "1"</code> in Can-Mar will therefore discard real length data in at least 42% of these groups. See <a href="#sec-canmar-specval">Can-Mar SpeciesValidity=“5” anomaly</a> in the issues document.</p>
<p><strong>Practical implication:</strong> if you aggregate over <code>.id × aphia</code> without also grouping on <code>SpeciesValidity</code>, rows from different record types will be silently mixed together. For most surveys (including BTS), <strong>filter to <code>SpeciesValidity == "1"</code> before aggregating</strong> to retain only the full length-frequency records. For Can-Mar, the appropriate treatment of <code>SpeciesValidity = "5"</code> rows with length data is currently unresolved.</p>
<p>See the <a href="#vocab-specval">SpeciesValidity vocabulary</a> in D2.2 for the full code list, and <a href="#sec-specval-variation">HL grouping key constancy violations</a> in the issues document for per-survey statistics.</p>
<hr>
</section>
</section>
<section id="version-history" class="level2">
<h2 class="anchored" data-anchor-id="version-history">Version history</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 37%">
<col style="width: 25%">
<col style="width: 37%">
</colgroup>
<thead>
<tr class="header">
<th>Version</th>
<th>Date</th>
<th>Changes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>3.0</td>
<td>2014</td>
<td>Original ICES DATRAS FAQs document</td>
</tr>
<tr class="even">
<td>4.0 (IMBUS)</td>
<td>June 2026</td>
<td>Restructured; field names updated to current standard (legacy names in parentheses); DataType <code>P</code> added throughout; survey list updated to 29 surveys; coordinates corrected to decimal degrees; IMBUS-added questions marked <strong>[IMBUS]</strong> and collected in §IMBUS Additions</td>
</tr>
</tbody>
</table>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>